version: '3'
services:
  db:
    image: postgres:15
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  web:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "rm -f /tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3001"
    ports:
      - 3001:3001
    volumes:
      - .:/weather-app-api
    environment:
      ipinfo_access_token: "849a2b9f054c7f"
      open_weather_api_key: "bae44955786024a7fc5c3ca0be361f95"
      accu_weather_api_key: "m20jD1qG0JIcEPaX34BxXdSBOWuX7UWU"

volumes:
  postgres:
